{"pdb_id": "1a51", "chain_1_id": null, "chain_2_id": null, "type": "chain", "assembly_id": 1, "error": "DataPipeline.get_data_bioassembly() got an unexpected keyword argument 'mmcif_fpath' at idx 0:\nTraceback (most recent call last):\n  File \"/home/ubuntu/shafi_workspace/Protenix/protenix/data/dataset.py\", line 301, in __getitem__\n    data = self.process_one(idx)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/shafi_workspace/Protenix/protenix/data/dataset.py\", line 429, in process_one\n    self._get_bioassembly_data(idx=idx)\n  File \"/home/ubuntu/shafi_workspace/Protenix/protenix/data/dataset.py\", line 326, in _get_bioassembly_data\n    bioassembly_dict = DataPipeline.get_data_bioassembly(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: DataPipeline.get_data_bioassembly() got an unexpected keyword argument 'mmcif_fpath'\n"}